#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_MACH_XIAOMI_CEPHEUS)	+= goodix_ta/
obj-$(CONFIG_MACH_XIAOMI_CRUX)	+= goodix_ta_crux/
obj-$(CONFIG_MACH_XIAOMI_RAPHAEL)        += goodix_fod_thy/
